### ISSUE TITLE
How to add this tool on blogger.com, tell me step by step.

### ISSUE THREAD

**Issue by Asabur1115** [OddDevelopment/Simple-Adblock-Detector#1]
Hi, I tried to use anti-ad blogger as per your big no on my blogger website (blogger.com), but I can't. Please tell me step by step how I can set this tool in my blogger.

**Comment by OddDevelopment** [comment]
1. Go to the "Layout" page on the sidebar on the blogger dashboard
2. Add an "HTML/Javascript" widget to the side bar section of your site with no title and the content 
```
<script src="https://odd.rip/cdn/script.js"></script>
```
4. Make a "disable-adblock" page so its not redirecting to nothing
5. You should be good to go! Please give this project a star on github <3
